const $=s=>document.querySelector(s);let q=[];let cap=8;let first=0;let last=0;let next=10;let wrapped=false;
const cells=$('#cells'),trace=$('#trace'),feedback=$('#feedback');
function log(s){const li=document.createElement('li');li.textContent=s;trace.prepend(li)}
function draw(){cells.innerHTML='';const physical=Array(cap).fill('');q.forEach((v,i)=>physical[(first+i)%cap]=v);physical.forEach((v,i)=>{const d=document.createElement('div');d.className='cell'+(q.length&&i===first?' first':'')+(i===last?' last':'');d.innerHTML=`<small>${i}</small>${v}`;cells.append(d)});$('#cap').textContent=cap;$('#size').textContent=q.length;$('#first').textContent=first;$('#last').textContent=last}
function unlock(){wrapped=true;$('#decision').classList.remove('locked');$('#decision').classList.add('unlocked');feedback.textContent='Wraparound erreicht: Die grüne first-Zelle liegt physisch hinter last. Entscheide jetzt die Kopierreihenfolge.'}
$('#enter').onclick=()=>{const value=Number($('#value').value);if(q.length===cap){cap*=2;first=0;last=q.length;log(`grow → capacity ${cap}; logische Reihenfolge bleibt`)}q.push(value);last=(first+q.length)%cap;log(`enter ${value} | size ${q.length}, cap ${cap}`);$('#value').value=++next;if(first>last)unlock();draw()};
$('#leave').onclick=()=>{if(!q.length){feedback.textContent='Underflow: Eine leere Queue hat kein front.';return}const v=q.shift();first=(first+1)%cap;if(q.length*4<cap&&cap>8){cap=Math.max(8,cap/2);first=0;last=q.length;log(`shrink → capacity ${cap} (Auslastung strikt <25%)`)}else last=(first+q.length)%cap;log(`leave → ${v} | size ${q.length}, cap ${cap}`);feedback.textContent=`FIFO liefert ${v}.`;draw()};
$('#reset').onclick=()=>{q=[];cap=8;first=last=0;wrapped=false;trace.innerHTML='';$('#decision').className='decision locked';$('#gate').className='gate locked';feedback.textContent='Starte mit drei bis acht enter-Schritten.';draw()};
document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const kind=b.dataset.choice,out=$('#decision-feedback');if(kind==='logical'){out.textContent='Richtig: Resize linearisiert die logische FIFO-Folge; first wird 0 und last wird size.';$('#decision').classList.add('correct');$('#gate').className='gate unlocked'}else if(kind==='physical'){out.textContent='Blockiert: Nach Wraparound zerstört physisches Kopieren die FIFO-Reihenfolge. Beginne bei first und gehe modulo capacity.';$('#decision').classList.add('wrong')}else{out.textContent='Blockiert: Die Aufgabe sagt unter 25 %, nicht bei 25 %. Nutze size*4 < capacity; außerdem nie unter 8.';$('#decision').classList.add('wrong')}});
const todos=['Implementiere zuerst resize_queue: logisch ab first kopieren.','Dann enter: an last schreiben, last modulo capacity, size erhöhen.','Zum Schluss leave: front sichern, first/size ändern, danach strikt <25 % prüfen.'];let ti=0;$('#reveal').onclick=()=>{$('#todo').textContent=todos[Math.min(ti++,todos.length-1)]};
document.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>{const key='ads-uebungsblaetter-state-v1',state=JSON.parse(localStorage.getItem(key)||'{}');state.pb07a01=b.dataset.mark;localStorage.setItem(key,JSON.stringify(state));$('#saved').textContent=`Gespeichert: ${b.textContent}`});draw();
