(() => {
  const STORAGE_KEY='ads-uebungsblaetter-state-v1', FIELD='pb07a04';
  const $=selector=>document.querySelector(selector); let words=[],position=-1;
  const queues=Array.from({length:26},(_,i)=>({letter:String.fromCharCode(97+i),items:[]}));
  function renderQueues(){ $('#queues').innerHTML=queues.map(q=>`<div class="queue${q.items.length?' active':''}"><strong>${q.letter}</strong>${q.items.map(w=>`<span>${w}</span>`).join('')}</div>`).join(''); }
  function parse(){const values=$('#words').value.split(/[,\s]+/).filter(Boolean);if(!values.length)return {error:'Gib mindestens ein Wort ein.'};const d=values[0].length;if(values.some(w=>w.length!==d||!/^[a-z]+$/.test(w)))return {error:'Blockiert: Alle Wörter müssen dieselbe Länge haben und nur lowercase a–z enthalten.'};return {values,d};}
  function load(){const result=parse();if(result.error){$('#trace-feedback').className='feedback try';$('#trace-feedback').textContent=result.error;return false;}words=result.values;position=result.d-1;queues.forEach(q=>q.items=[]);renderQueues();$('#position').textContent=`Start bei Position ${position} (d − 1)`;$('#order').textContent=words.join(' · ');$('#trace-feedback').className='feedback';$('#trace-feedback').textContent='Bereit: nächste Runde verteilt stabil in die 26 Queues.';return true;}
  function round(){if(!words.length&&!load())return;if(position<0){$('#trace-feedback').textContent='Fertig: alle d Positionen wurden bearbeitet.';return;}queues.forEach(q=>q.items=[]);words.forEach(word=>queues[word.charCodeAt(position)-97].items.push(word));renderQueues();words=queues.flatMap(q=>q.items);$('#position').textContent=`Runde an Position ${position}`;$('#order').textContent=words.join(' · ');position-=1;$('#trace-feedback').className='feedback good';$('#trace-feedback').textContent=position<0?'Sortiert: stabil von a bis z eingesammelt. Jetzt FIFO begründen.':'Stabil a … z eingesammelt. Nächste Runde geht eine Position nach links.';$('#stability').hidden=false;}
  document.querySelectorAll('[data-path]').forEach(button=>button.addEventListener('click',()=>{const ok=button.dataset.path==='lsd',out=$('#gate-feedback');out.hidden=false;out.className=`feedback ${ok?'good':'try'}`;out.textContent=ok?'Richtig: LSD beginnt bei d − 1 und wandert bis Position 0. Der Trace ist entsperrt.':'Blockiert: Position 0 zuerst wäre MSD. Ohne rekursive Untergruppen reicht bloßes Weitersortieren nach rechts nicht.';$('#playground').hidden=!ok;if(ok){renderQueues();$('#playground').scrollIntoView({behavior:'smooth',block:'start'});}}));
  document.querySelectorAll('[data-stability]').forEach(button=>button.addEventListener('click',()=>{const ok=button.dataset.stability==='fifo',out=$('#stability-feedback');out.hidden=false;out.className=`feedback ${ok?'good':'try'}`;out.textContent=ok?'Richtig: FIFO erhält innerhalb eines Buckets die Reihenfolge der vorherigen Runde. Das Lab ist entsperrt.':'Blockiert: LIFO kehrt gleiche Buckets um und zerstört damit die Stabilität der vorherigen Runde.';$('#lab').hidden=!ok;if(ok)$('#lab').scrollIntoView({behavior:'smooth',block:'start'});}));
  $('#load').addEventListener('click',load);$('#round').addEventListener('click',round);$('#reset').addEventListener('click',()=>{words=[];position=-1;queues.forEach(q=>q.items=[]);renderQueues();$('#position').textContent='Bereit';$('#order').textContent='–';$('#trace-feedback').className='feedback';$('#trace-feedback').textContent='Lade eine kleine Wortliste. Erlaubt sind nur gleich lange Wörter aus a–z.';});
  document.querySelectorAll('[data-hint]').forEach(button=>button.addEventListener('click',()=>{const hint=document.getElementById(button.dataset.hint);hint.hidden=!hint.hidden;button.setAttribute('aria-expanded',String(!hint.hidden));}));
  document.querySelectorAll('[data-state]').forEach(button=>button.addEventListener('click',()=>{if(!$('#proof').checked){$('#state-feedback').textContent='Erst sortierte Wortliste und grüne Tests bestätigen.';return;}let state={};try{state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(_){state={}}state[FIELD]=button.dataset.state;localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$('#state-feedback').textContent=`Gespeichert: ${button.dataset.state==='sitzt'?'Sitzt':'Wackelt'}.`;}));
  renderQueues();
})();
